language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: src/Loggy.sln
script:
 - dotnet restore
 - dotnet restore
global:
 - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
 - DOTNET_CLI_TELEMETRY_OPTOUT=1